# Generated by Django 4.1.7 on 2023-03-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_users_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
