# Generated by Django 4.1.7 on 2023-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('authentication', '0003_rename_first_name_users_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='author_users', to='projects.projects'),
        ),
    ]
