# Generated by Django 4.1.7 on 2023-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_remove_users_projects'),
        ('projects', '0003_issue_project_rename_comments_comment_delete_issues_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(null=True, related_name='user_projects', through='projects.Contributors', to='projects.project'),
        ),
    ]
