# Generated by Django 4.1.7 on 2023-04-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_remove_users_projects'),
        ('projects', '0002_projects_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('HIGH', 'High')], default='Low', max_length=10)),
                ('tag', models.CharField(choices=[('Bug', 'Bug'), ('Improuvement', 'Improvement'), ('Task', 'Task')], default='Bug', max_length=15)),
                ('status', models.CharField(choices=[('To do', 'To Do'), ('Work in process', 'Wip'), ('Done', 'Done')], default='To do', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('type', models.CharField(choices=[('Back-end', 'Back End'), ('Front-end', 'Front End'), ('IOS', 'Ios'), ('Android', 'Android')], default='Back-end', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to='authentication.user')),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
        migrations.AddField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('Admin', 'Admin'), ('list', 'List'), ('Delete', 'Delete'), ('Update', 'Update')], default='Admin', max_length=15),
        ),
        migrations.AddField(
            model_name='contributors',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='contributor', through='projects.Contributors', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
